# Generated by Django 5.1.5 on 2026-01-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_recording',
            field=models.FileField(blank=True, null=True, upload_to='profiles/voices/'),
        ),
    ]
