# Generated by Django 5.1.3 on 2026-03-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0002_user_address_user_full_name_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
